<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>speedy_teleop</name>
  <version>1.0.0</version>
  <description>Pacote de interface de controle manual (Teleop) e ponte serial.</description>
  <maintainer email="nycolascanutto@gmail.com">nycocado</maintainer>
  <license>Proprietary</license>

  <!-- Ferramenta de build necessária para processar este pacote -->
  <buildtool_depend>ament_python</buildtool_depend>

  <!-- Dependências de execução -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>joy</exec_depend>

  <!-- Dependências apenas para execução de testes unitários -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
