---
- name: Base system (RPi OS)
  block:
    - name: Update APT cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install essential tools
      ansible.builtin.apt:
        name: [vim, v4l-utils, i2c-tools, rfkill, htop]
        state: present

    - name: Ensure EEPROM is up to date
      ansible.builtin.command: rpi-eeprom-update -a
      register: eeprom_status
      changed_when: "'BOOTLOADER: up-to-date' not in eeprom_status.stdout"
