---
- name: 04 - Hardware e Periféricos
  block:
    - name: Instalar ferramentas de hardware (dtc, i2c)
      ansible.builtin.apt:
        name: [dphys-swapfile, device-tree-compiler, libi2c-dev, i2c-tools]
        state: present

    - name: Aumentar o tamanho do SWAP (4GB) para evitar travamentos no colcon build
      ansible.builtin.lineinfile:
        path: /etc/dphys-swapfile
        regexp: '^#?CONF_SWAPSIZE='
        line: 'CONF_SWAPSIZE=4096'
        create: yes

    - name: Remover limite máximo de SWAP (CONF_MAXSWAP)
      ansible.builtin.lineinfile:
        path: /etc/dphys-swapfile
        regexp: '^#?CONF_MAXSWAP='
        line: 'CONF_MAXSWAP=4096'
      register: swap_config

    - name: Garantir parametros de fsck no cmdline.txt
      ansible.builtin.replace:
        path: /boot/firmware/cmdline.txt
        regexp: '^((?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      loop:
        - "fsck.repair=yes"
        - "fsck.mode=force"

    - name: Aplicar nova configuração de SWAP
      ansible.builtin.shell: |
        dphys-swapfile swapoff
        dphys-swapfile setup
        dphys-swapfile swapon
      when: swap_config.changed

    - name: Configurar Overlays e Parâmetros no config.txt
      ansible.builtin.lineinfile:
        path: /boot/firmware/config.txt
        line: "{{ item.line }}"
        regexp: "{{ item.regexp | default(omit) }}"
        state: present
      loop:
        - { line: "dtparam=audio=off", regexp: "^dtparam=audio=" }
        - { line: "dtparam=i2c_arm=on", regexp: "^dtparam=i2c_arm=" }
        - { line: "dtparam=spi=off", regexp: "^dtparam=spi=" }
        - { line: "camera_auto_detect=1", regexp: "^camera_auto_detect=" }
        - { line: "dtoverlay=ov5647,cam0", regexp: "^dtoverlay=ov5647" }
        - { line: "dtoverlay=pwm-2chan,pin=12,func=4,pin2=13,func2=4", regexp: "^dtoverlay=pwm-2chan" }

    - name: Garantir que o modulo i2c-dev carrega no boot
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: "i2c-dev"
        state: present

    - name: Configurar regras de udev para Periféricos
      ansible.builtin.copy:
        dest: "/etc/udev/rules.d/{{ item.name }}"
        content: "{{ item.content }}"
        mode: '0644'
      loop:
        - { name: '10-ldlidar.rules', content: 'KERNEL=="ttyUSB*", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", MODE:="0666", GROUP:="dialout", SYMLINK+="ldlidar"' }
        - { name: '12-pwm.rules', content: 'SUBSYSTEM=="pwm", KERNEL=="pwmchip*", ACTION=="add", RUN+="/bin/chgrp -R gpio /sys%p", RUN+="/bin/chmod -R g+w /sys%p"' }
        - { name: '99-gpio.rules', content: 'SUBSYSTEM=="gpio", KERNEL=="gpiochip*", ACTION=="add", GROUP="gpio", MODE="0660"' }
        - { name: '99-gpiomem.rules', content: 'KERNEL=="gpiomem", GROUP="gpio", MODE="0660"' }
        - { name: '99-i2c.rules', content: 'KERNEL=="i2c-[0-9]*", GROUP="i2c", MODE="0660"' }
        - { name: '99-joy.rules', content: 'KERNEL=="js*", MODE="0666", GROUP="input"' }

    - name: Garantir que o grupo gpio existe
      ansible.builtin.group:
        name: gpio
        state: present

    - name: Adicionar utilizador aos grupos de hardware
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: "dialout,video,i2c,gpio,render,input"
        append: yes

    - name: Recarregar regras de udev
      ansible.builtin.shell: |
        udevadm control --reload-rules
        udevadm trigger
