---
- name: Hardware e GUI (RPi)
  block:
    - name: Desabilitar detecção automática de câmera (para OV5647 clone)
      ansible.builtin.lineinfile:
        path: /boot/firmware/config.txt
        regexp: '^camera_auto_detect='
        line: 'camera_auto_detect=0'
        state: present
      become: yes

    - name: Configurar porta da câmera (Default cam0)
      ansible.builtin.set_fact:
        target_cam_port: "{{ camera_port | default('cam0') }}"

    - name: Configurar overlay da câmera OV5647 (Pi 5 com link-frequency)
      ansible.builtin.lineinfile:
        path: /boot/firmware/config.txt
        regexp: '^dtoverlay=ov5647'
        line: "dtoverlay=ov5647,{{ target_cam_port }},link-frequency=220500000"
        state: present
      become: yes

    - name: Configurar regras de udev para o LiDAR
      ansible.builtin.copy:
        src: "../../software/src/ldlidar_ros2/scripts/ldlidar.rules"
        dest: "/etc/udev/rules.d/10-ldlidar.rules"
        mode: '0644'
      become: yes

    - name: Configurar regras de udev para o ESP32-S3
      ansible.builtin.copy:
        dest: "/etc/udev/rules.d/11-esp32.rules"
        content: 'KERNEL=="ttyACM*", ATTRS{idVendor}=="303a", ATTRS{idProduct}=="1001", MODE:="0777", SYMLINK+="ttyESP32"'
        mode: '0644'
      become: yes

    - name: Recarregar regras de udev
      ansible.builtin.shell: |
        udevadm control --reload-rules
        udevadm trigger
      become: yes

    - name: Configurar grupos de usuários
      ansible.builtin.user: { name: "{{ ansible_user }}", groups: "dialout,video,i2c", append: yes }

    - name: Instalar ambiente desktop (opcional)
      ansible.builtin.apt: { name: xubuntu-desktop, state: present }
      when: install_gui | default(false)

    - name: Configurar inicialização XFCE
      ansible.builtin.copy:
        dest: "/home/{{ ansible_user }}/.xinitrc"
        content: "exec startxfce4"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      when: install_gui | default(false)
