---
- name: Sync ROS 2 workspace
  block:
    - name: Ensure base directories
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "speedy_ws/src"
      become: no

    - name: Sync software source code
      ansible.posix.synchronize:
        src: "../../software/src/"
        dest: "/home/{{ ansible_user }}/speedy_ws/src/"
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=build"
          - "--exclude=install"
          - "--exclude=log"
          - "--exclude=__pycache__"
          - "--exclude=deps/imu_tools/rviz_imu_plugin"
          - "--exclude=deps/vision_msgs/vision_msgs_rviz_plugins"
      become: no
