---
- name: Auto-start service
  block:
    - name: Sync CycloneDDS configuration
      ansible.builtin.copy:
        src: ../files/cyclonedds.xml
        dest: "/home/{{ ansible_user }}/speedy_ws/cyclonedds.xml"
        mode: "0644"

    - name: Copy Speedy systemd service file
      ansible.builtin.template:
        src: ../files/speedy.service
        dest: /etc/systemd/system/speedy.service
        mode: "0644"
      register: service_file

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
      when: service_file.changed

    - name: Enable service on boot
      ansible.builtin.systemd:
        name: speedy
        enabled: yes
        state: restarted
