---
- name: Setup do Robô Speedy (Raspberry Pi OS Lite + Rospian Nativo)
  hosts: robots
  become: yes
  tasks:
    - name: "Passo 01: Sistema Base"
      ansible.builtin.include_tasks:
        file: 01_base.yml
        apply:
          tags: [base]
      tags: [base]
    - name: "Passo 02: Rede e Acesso"
      ansible.builtin.include_tasks:
        file: 02_network.yml
        apply:
          tags: [network]
      tags: [network]
    - name: "Passo 03: Shell e Dotfiles"
      ansible.builtin.include_tasks:
        file: 03_shell.yml
        apply:
          tags: [shell]
      tags: [shell]
    - name: "Passo 04: Hardware e Overlays"
      ansible.builtin.include_tasks:
        file: 04_hardware.yml
        apply:
          tags: [hardware]
      tags: [hardware]
    - name: "Passo 05: Dependências APT (Host)"
      ansible.builtin.include_tasks:
        file: 05_extra_packages.yml
        apply:
          tags: [packages]
      tags: [packages]
#   - name: "Passo 06: Compilar libcamera (RPI Nativo)"
#     ansible.builtin.include_tasks:
#       file: 06_libcamera_source.yml
#       apply:
#         tags: [libcamera]
#     tags: [libcamera]
    - name: "Passo 07: ROS 2 Nativo (Rospian)"
      ansible.builtin.include_tasks:
        file: 07_rospian.yml
        apply:
          tags: [ros]
      tags: [ros]
    - name: "Passo 08: Workspace ROS 2 (Sincronização e Patches)"
      ansible.builtin.include_tasks:
        file: 08_workspace.yml
        apply:
          tags: [workspace, deploy]
      tags: [workspace, deploy]
    - name: "Passo 09: Compilação do Workspace"
      ansible.builtin.include_tasks:
        file: 09_workspace_build.yml
        apply:
          tags: [build, deploy]
      tags: [build, deploy]
    - name: "Passo 10: Auto-Start (Serviço Systemd)"
      ansible.builtin.include_tasks:
        file: 10_service.yml
        apply:
          tags: [service, deploy]
      tags: [service, deploy]
    - name: "Passo 11: Otimização de Performance (Real-Time)"
      ansible.builtin.include_tasks:
        file: 11_performance.yml
        apply:
          tags: [performance]
      tags: [performance]
