---
- name: Host machine setup
  hosts: host
  tasks:
    - name: "01 - Hardware permissions"
      block:
        - name: Add user to dialout group (serial/ESP32 access)
          ansible.builtin.user:
            name: "{{ ansible_user_id }}"
            groups: dialout
            append: yes
          become: yes

    - name: "02 - Network and firewall"
      block:
        - name: Enable network services
          ansible.builtin.service:
            name: "{{ item }}"
            state: started
            enabled: yes
          loop: [avahi-daemon, sshd]
          become: yes

        - name: Configure firewall rules
          ansible.posix.firewalld:
            service: "{{ item }}"
            state: enabled
            permanent: yes
            immediate: yes
          loop: [mdns, ssh]
          become: yes
          ignore_errors: yes

        - name: Share IPv4 over eth0
          ansible.builtin.shell: nmcli con modify "Wired connection 1" ipv4.method shared
          become: yes
          ignore_errors: yes
