---
- name: 01 - Shell e Dotfiles
  block:
    - name: Atualizar cache e instalar pacotes base
      ansible.builtin.apt:
        update_cache: yes
        name: [zsh, git, curl, wget]
        state: present
      become: yes

    - name: Verificar se o Oh My Zsh já está instalado
      ansible.builtin.stat:
        path: "~/.oh-my-zsh"
      register: omz_dir

    - name: Instalar Oh My Zsh
      ansible.builtin.shell: 'curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh > /tmp/install_omz.sh && sh /tmp/install_omz.sh --unattended'
      when: not omz_dir.stat.exists

    - name: Clonar plugins Zsh
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "~/.oh-my-zsh/custom/{{ item.path }}"
        depth: 1
        update: no
      loop:
        - { repo: 'https://github.com/romkatv/powerlevel10k.git', path: 'themes/powerlevel10k' }
        - { repo: 'https://github.com/zsh-users/zsh-autosuggestions', path: 'plugins/zsh-autosuggestions' }
        - { repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git', path: 'plugins/zsh-syntax-highlighting' }
        - { repo: 'https://github.com/zsh-users/zsh-completions.git', path: 'plugins/zsh-completions' }

    - name: Configurar Zsh como shell padrão
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      become: yes

    # Os dotfiles já são copiados pelo script host/main.yml para a pasta speedy-home no host.
    # Mas se quisermos sincronizar de dentro do container:
    - name: Sincronizar dotfiles
      ansible.builtin.copy:
        src: "../files/{{ item }}"
        dest: "~/{{ item }}"
        mode: '0644'
      loop: [.zshrc, .p10k.zsh]
