---
- name: 02 - ROS 2 Desktop e Foxglove (Distrobox)
  block:
    - name: Adicionar repositório ROS 2 dentro do container
      ansible.builtin.command:
        cmd: |
          distrobox enter -n speedy-dev -- sudo sh -c '
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu noble main" > /etc/apt/sources.list.d/ros2.list
          apt-get update'
      changed_when: false

    - name: Instalar ROS 2 Desktop e ferramentas dentro do container
      ansible.builtin.command:
        cmd: 'distrobox enter -n speedy-dev -- sh -c "sudo apt-get install -y ros-jazzy-desktop ros-dev-tools ros-jazzy-foxglove-bridge"'
      changed_when: false

    - name: Instalar Foxglove Studio (Link Oficial Permanente)
      ansible.builtin.command:
        cmd: 'distrobox enter -n speedy-dev -- sh -c "wget https://get.foxglove.dev/desktop/latest/foxglove-studio-latest-linux-amd64.deb -O /tmp/foxglove.deb && sudo apt install -y /tmp/foxglove.deb && rm /tmp/foxglove.deb"'
      changed_when: false

    - name: Rosdep init/update dentro do container
      ansible.builtin.command:
        cmd: |
          distrobox enter -n speedy-dev -- sh -c '
          [ -f /etc/ros/rosdep/sources.list.d/20-default.list ] || sudo rosdep init
          rosdep update'
      changed_when: false
