---
- name: 02 - ROS 2 Desktop e Foxglove Studio
  block:
    - name: Garantir dependências do repositório
      ansible.builtin.apt:
        name: [curl, gnupg2, python3-pip]
        state: present
      become: yes

    - name: Importar a chave GPG do ROS 2
      ansible.builtin.shell: |
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/ros-archive-keyring.gpg
      become: yes

    - name: Adicionar o repositório APT do ROS 2 (Noble)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu noble main"
        state: present
        filename: ros2
      become: yes

    - name: Instalar ROS 2 Desktop e Foxglove Bridge
      ansible.builtin.apt:
        update_cache: yes
        name: 
          - ros-jazzy-desktop
          - ros-jazzy-rmw-cyclonedds-cpp
          - python3-rosdep
          - colcon
          - python3-colcon-ros
          - python3-colcon-common-extensions
        state: present
      become: yes

    - name: Inicializar rosdep (sudo)
      ansible.builtin.command: rosdep init
      register: rosdep_init
      failed_when: false
      changed_when: rosdep_init.rc == 0
      become: yes

    - name: Baixar pacote Debian do Foxglove Studio
      ansible.builtin.get_url:
        url: https://get.foxglove.dev/desktop/latest/foxglove-studio-latest-linux-amd64.deb
        dest: /tmp/foxglove.deb
        mode: '0644'
      become: no

    - name: Instalar Foxglove Studio
      ansible.builtin.apt:
        deb: /tmp/foxglove.deb
        state: present
      become: yes

    - name: Limpar instalador do Foxglove
      ansible.builtin.file:
        path: /tmp/foxglove.deb
        state: absent
      become: no
