---
- name: "Distrobox: create speedy-dev container"
  hosts: host
  tags: [container, setup]
  tasks:
    - name: "01 - Dev container"
      ansible.builtin.include_tasks: 01_container.yml

- name: "Distrobox: provision speedy-dev container"
  hosts: dev
  tasks:
    - name: "02 - Shell and dotfiles"
      ansible.builtin.include_tasks: 02_shell.yml
    - name: "03 - ROS 2 Desktop and Foxglove"
      ansible.builtin.include_tasks: 03_ros2_desktop.yml
    - name: "04 - PC workspace"
      ansible.builtin.include_tasks: 04_pc_workspace.yml
