image_width: 640
image_height: 480
camera_name: speedy_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [263.32594,   0.     , 327.21686,
           0.     , 263.16175, 246.08267,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.240594, 0.045436, 0.000390, 0.002668, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [188.30398,   0.     , 331.401  ,   0.     ,
           0.     , 195.13131, 251.51915,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
