controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # Controlador de Bicicleta (1 Motor, 1 Servo) - Ideal para Jazzy
    bicycle_steering_controller:
      type: bicycle_steering_controller/BicycleSteeringController

    # Controladores Manuais (Pass-through direto para o hardware)
    manual_steering_controller:
      type: forward_command_controller/ForwardCommandController
      
    manual_drive_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

manual_steering_controller:
  ros__parameters:
    joints:
      - steering_joint
    interface_name: position

manual_drive_controller:
  ros__parameters:
    joints:
      - drive_joint
    interface_name: velocity

bicycle_steering_controller:
  ros__parameters:
    traction_joints_names: [drive_joint]
    steering_joints_names: [steering_joint]

    # Dimensões (Speedy)
    wheelbase: 0.251 
    track_width: 0.139
    traction_wheel_radius: 0.0325

    # Limites
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    
    angular.z.has_position_limits: true
    angular.z.max_position: 0.4363
    angular.z.min_position: -0.4363

    # Odometria e Entrada
    use_stamped_vel: true
    odom_frame_id: odom
    base_frame_id: base_link
    publish_rate: 50.0


