# Configurações de Hardware do Speedy
speedy_hardware:
  ros__parameters:
    # --- Limites Mecânicos ---
    max_steering_angle_left_deg: 25.0
    max_steering_angle_right_deg: 25.0
    steering_trim_deg: 0.0

    # --- Mapeamento de Pinos (RPi 5) ---
    pin_motor_en_1: 17
    pin_motor_en_2: 27
    pin_motor_fwd_ch: 0
    pin_motor_fwd: 12
    pin_motor_rev_ch: 1
    pin_motor_rev: 13
    pin_servo_ch: 3
    pin_servo: 15
    pin_hall: 24

    # --- Configurações de Tração ---
    motor_period_ns: 50000
    motor_min_effort: 0.05
    motor_deadband_ms: 10
    motor_invert_direction: false

    # --- Configurações de Direção ---
    steering_pwm_freq_hz: 50.0
    steering_center_pulse_ms: 1.5
    steering_max_deflection_ms: 1.0
    steering_nominal_range_deg: 45.0
    steering_use_polynomial: true
    steering_poly_a2: 0.000333
    steering_poly_a1: 0.028469
    steering_poly_a0: 1.481
    steering_max_speed_deg_per_sec: 0.0
    steering_invert_direction: false
    
    # --- Controle e Cinemática ---
    wheel_radius: 0.0325
    gear_ratio: 2.3
    magnets_per_rev: 4
    pid_kp: 0.6
    pid_ki: 0.4
    pid_kd: 0.0
    pid_deadband_m_s: 0.01
    velocity_filter_alpha: 0.02
