racing_teleop_node:
  ros__parameters:
    axis_steering: 0
    axis_throttle: 4
    axis_brake: 5
    deadzone: 0.05
    # Os limites de velocidade e escala são injetados via launch do controllers.yaml
