[sim]
raspberrypi-sim ansible_connection=podman

[dev]
speedy-dev ansible_connection=podman

[robots]
speedy_pi ansible_host=raspberrypi.local ansible_user=speedy

[host]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3
