obstacle_detector:
  ros__parameters:
    enabled: true
    model_dir: ''             # vazio = share/speedy_vision_pc/models/obstacle_detector
    model_file: 'model.onnx'  # nome do ficheiro exportado
    input_size: 640           # imgsz aumentado para o PC
    conf_threshold: 0.35
    nms_threshold: 0.45
    max_rate_hz: 0.0          # sem teto no PC (RTX 4060)
    publish_overlay: true
    undistort: false          # Desligado para não causar desalinhamento no overlay do Foxglove
    use_compressed: true      # PC recebe do robot via wifi
    image_topic: '/speedy_camera/image_raw'
